# Generated by Django 4.1.2 on 2023-01-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admindb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mob', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('pswd', models.CharField(blank=True, max_length=50, null=True)),
                ('cpswd', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
